#!/bin/sh

cd _pages

printf "// Generated by prepare.sh!!!\nexport const PAGES = [\n" > ../pages.js

for page in $(ls .); do
    echo "    \"$page\"," >> ../pages.js
done

printf "]\n" >> ../pages.js

cd ..
